import Head from 'next/head'
import Image from 'next/image'
import Feed from '../components/home/Feed'
import Sidebar from '../components/Sidebar'
import Widget from '../components/Widget'
import styles from '../styles/Home.module.css'
import { TwitterContext } from '../context/TwitterContext'
import { useContext } from 'react'
import Logo from '../images/logo.png'
import errorImg from '../images/error.png'

export default function Home() {
  const { appStatus, connectWallet } = useContext(TwitterContext)

  const app = (status = appStatus) => {
    switch (status) {
      case 'connected':
        return userLoggedIn

      case 'notConnected':
        return noUserFound

      case 'noMetaMask':
        return noMetaMaskFound

      case 'error':
        return error

      default:
        return loading
    }
  }

  const userLoggedIn = (
    <div className='flex justify-center h-screen w-screen bg-[#15202b] text-white'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='max-w-[1400px] md:w-2/3 flex md:justify-between'>
        <Sidebar className='hidden md:blockx' />
        <Feed />
        <Widget className='hidden md:block' />
      </div>
    </div>
  )

  const noMetaMaskFound  = (
    <div className='w-full h-full flex flex-col justify-center items-center pb-48'>
      <Image src={Logo} width={200} height={200} />
      <a 
      href={`https://metamask.io/download.html`}
      rel = "noreferrer"
      target="_blank">
        You must install Metamsk
      </a>
    </div>
  )

  const noUserFound = (
    <div className='w-full h-full flex flex-col justify-center items-center pb-48'>
      <Image src={Logo} width={200} height={200} />
      <div
        className='text-2xl text-black bg-white font-bold mb-[-3rem] mt-[3rem] px-6 py-4 rounded-full cursor-pointer hover:bg-[#d7dbdc]'
        onClick={() => connectWallet()}
      >
        Connect Wallet
      </div>
      <div className='text-3xl font-bold text-center mt-24'>Connect to Metamask.</div>
    </div>
  )

  const loading = (
    <div className='w-full h-full flex flex-col justify-center items-center pb-48'>
      <div className='text-3xl font-bold text-center mt-24'>Loading...</div>
    </div>
  )

  const error = (
    <div className='w-full h-full flex flex-col justify-center items-center pb-48'>
      <Image src={errorImg} width={250} height={200} />
      <div className='text-3xl font-bold text-center mt-24'>
        An error occurred. Please try again later or from another browser.
      </div>
    </div>
  )

  return (
    <div className='flex justify-center h-screen w-screen select-none bg-[#15202b] text-white'>{app(appStatus)}</div>
  )
}
